# Generated by Django 5.0.6 on 2024-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('credit', models.IntegerField(default=0, verbose_name='Кредит')),
                ('percetn', models.IntegerField(choices=[(16, '16%'), (18, '18%'), (22, '22%'), (24, '24%')], default=24, verbose_name='Процентная ставка')),
                ('duration', models.IntegerField(default=12, verbose_name='Срок погашения')),
            ],
        ),
    ]
