# Generated by Django 5.0.6 on 2024-06-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='percetn',
            new_name='percent',
        ),
    ]
